services:
  krakend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: krakend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - graphql_svc

  graphql_svc:
    build:
      context: ./graphql_svc
    expose:
      - "8000"

  svc_a:
    build:
      context: ./svc_a
    environment:
      KRAKEND_URL: http://krakend:8080/soap/cx
    ports:
      - "8001:8001"
    depends_on:
      - krakend

  web_ui:
    build:
      context: ./web_ui
    environment:
      KRAKEND_URL: http://krakend:8080/soap/cx
      GRAPHQL_URL: http://graphql_svc:8000/graphql
      MAPPING_FILE: /app/mapping.json
    volumes:
      - ./mapping.json:/app/mapping.json:ro
    ports:
      - "8002:8002"
    depends_on:
      - krakend
      - graphql_svc
